using Tutorials
using Random
using Test

Random.seed!(0);

for (title,filename) in Tutorials.files
    # Create temporal modules to isolate and protect test scopes
    tmpmod = string("module_",randstring(['A':'Z'; '0':'9'], 12))
    tmpfile = joinpath(@__DIR__,tmpmod)
    isfile(tmpfile) && error("File $tmpfile already exists!")
    testpath = joinpath(@__DIR__,"../src", filename)
    open(tmpfile,"w") do f
      println(f, "# This file is automatically generated")
      println(f, "# Do not edit")
      println(f)
      println(f, "module $tmpmod include(\"$testpath\") end")
    end
    @time @testset "$title" begin include(tmpfile) end
    rm(tmpfile)
end 

module fsi_tutorial
using Test
@testset "fsi_tutorial" begin include("../src/fsi_tutorial.jl") end
end # module

